//AdminLogin
export const ADMIN_LOGIN_LOADING="ADMIN_LOGIN_LOADING";
export const ADMIN_LOGIN_SUCCESS="ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL="ADMIN_LOGIN_FAIL";

//CreateEmployee
export const CREATE_EMPLOYEE_LOADING="CREATE_EMPLOYEE_LOADING";
export const CREATE_EMPLOYEE_SUCCESS="CREATE_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_FAIL="CREATE_EMPLOYEE_FAIL";

//User Details
export const USER_DETAILS_LOADING="USER_DETAILS_LOADING";
export const USER_DETAILS_SUCCESS="USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL="USER_DETAILS_FAIL";

//Search User
export const SEARCH_USER_LOADING="SEARCH_USER_LOADING";
export const SEARCH_USER_SUCCESS="SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAIL="SEARCH_USER_FAIL";

//Update User
export const UPDATE_USER_LOADING="UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL="UPDATE_USER_FAIL";

//Delete User 
export const DELETE_USER_LOADING="DELETE_USER_LOADING";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL="DELETE_USER_FAIL";

//Create Projects
export const CREATE_PROJECT_LOADING="CREATE_PROJECT_LOADING";
export const CREATE_PROJECT_SUCCESS="CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL="CREATE_PROJECT_FAIL";

//Toggles
export const LOGIN_TOGGLE="LOGIN_TOGGLE";
export const TIME_SHEET_DATES="TIME_SHEET_DATES";
export const EDIT_USER_TOGGLE="EDIT_USER_TOGGLE";
export const ALL_BA="ALL_BA";
export const RESET_LOGIN="RESET_LOGIN";
//Get Project
export const GET_PROJECT_FAIL = "GET_PROJECT_FAIL"
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS"
export const GET_PROJECT_LOADING = "GET_PROJECT_LOADING"

//Update Project
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL"
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS"
export const UPDATE_PROJECT_LOADING = "UPDATE_PROJECT_LOADING"

//Delete Project
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL"
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS"
export const DELETE_PROJECT_LOADING = "DELETE_PROJECT_LOADING"

//Search Project
export const SEARCH_PROJECT_FAIL = "SEARCH_PROJECT_FAIL"
export const SEARCH_PROJECT_SUCCESS = "SEARCH_PROJECT_SUCCESS"
export const SEARCH_PROJECT_LOADING = "SEARCH_PROJECT_LOADING"

//Create Task
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL"
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS"
export const CREATE_TASK_LOADING = "CREATE_TASK_LOADING"

//Get Task
export const GET_TASK_FAIL = "GET_TASK_FAIL"
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS"
export const GET_TASK_LOADING = "GET_TASK_LOADING"
//Delete Task
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_LOADING = "DELETE_TASK_LOADING"
